#Premier exercice // API Ping simple
# Creation d'une spec OpenAPI basique avec :Une route GET/ping qui retourne "pong" en text/plain avec code 200
openapi: 3.0.3 # Version du standard OpenAPI
info: #Methadonnes de mon API (Titre, Description, Version)
    title: API Ping Simple
    description: Une API basique qui repond "pong" a un ping
    version: 1.0.0

paths: # LeS routes de mon API
    /ping: # La route demmandee
        get: #Methode HTTP
            summary: Endpoint de test ping
            description: retourne "pong" pour verifier que l'API fonctionne
            reponses: # les reponses possibles
                '200': Code de status HTTP
                    description: Succes - retourne pong
                    content: #Le format de la reponse 
                        text/plain: # Type de contenu (pas de JSON ici)
                            schema:
                                type: string
                                example: "pong"
