openapi: 3.0.3
info:
  title: API Gestion de Tâches
  description: API CRUD pour la gestion de tâches (todo list)
  version: 1.0.0

paths:
  /tasks:
    get:
      summary: Récupérer toutes les tâches
      description: Retourne la liste complète des tâches
      responses:
        '200':
          description: Liste des tâches récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              examples:
                tasks_list:
                  summary: Liste de tâches
                  value:
                    - id: 1
                      title: "Faire les courses"
                      completed: false
                    - id: 2
                      title: "Réviser pour l'examen"
                      completed: true

    post:
      summary: Créer de nouvelles tâches
      description: Crée une liste de nouvelles tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateTask'
            examples:
              new_tasks:
                summary: Nouvelles tâches à créer
                value:
                  - title: "Faire les courses"
                    completed: false
                  - title: "Appeler le médecin"
                    completed: false
      responses:
        '201':
          description: Tâches créées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              examples:
                created_tasks:
                  summary: Tâches créées avec leurs IDs
                  value:
                    - id: 1
                      title: "Faire les courses"
                      completed: false
                    - id: 2
                      title: "Appeler le médecin"
                      completed: false

    delete:
      summary: Supprimer plusieurs tâches
      description: Supprime une liste de tâches via leurs identifiants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
            examples:
              ids_to_delete:
                summary: IDs des tâches à supprimer
                value: [1, 3, 5]
      responses:
        '200':
          description: Tâches supprimées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              examples:
                deleted_tasks:
                  summary: Tâches supprimées
                  value:
                    - id: 1
                      title: "Faire les courses"
                      completed: false
                    - id: 3
                      title: "Réviser"
                      completed: true

  /tasks/{id}:
    get:
      summary: Récupérer une tâche par ID
      description: Retourne une tâche spécifique par son identifiant
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant unique de la tâche
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Tâche trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                single_task:
                  summary: Une tâche
                  value:
                    id: 1
                    title: "Faire les courses"
                    completed: false
        '404':
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                task_not_found:
                  summary: Tâche introuvable
                  value:
                    message: "Task not found"

    delete:
      summary: Supprimer une tâche
      description: Supprime une tâche spécifique et la retourne
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant unique de la tâche
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Tâche supprimée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                deleted_task:
                  summary: Tâche supprimée
                  value:
                    id: 1
                    title: "Faire les courses"
                    completed: false

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - completed
      properties:
        id:
          type: integer
          description: Identifiant unique de la tâche
          example: 1
        title:
          type: string
          description: Titre de la tâche
          example: "Faire les courses"
        completed:
          type: boolean
          description: Statut de completion de la tâche
          example: false

    CreateTask:
      type: object
      required:
        - title
        - completed
      properties:
        title:
          type: string
          description: Titre de la tâche
          example: "Faire les courses"
        completed:
          type: boolean
          description: Statut de completion de la tâche
          example: false

    Error:
      type: object
      properties:
        message:
          type: string
          description: Message d'erreur
          example: "Task not found"